alias bc='bc -l'
alias lh='ls -lh'
alias lha='ls -lha'
alias mkdir_now='date +%Y%m%d%H%M | xargs mkdir'
alias webshare='python -c "import SimpleHTTPServer;SimpleHTTPServer.test()"'
#alias cat='lolcat'
alias :q='echo This is not Vim you silly fool'
alias :w='echo This is not Vim you silly fool'
alias :wq='echo This is not Vim you silly fool'
alias pls='sudo $(history -p !!); history -d $((HISTCMD-1))'
# Get week number
alias week='date +%V'
